import type { LayerDefinition, SourceWorkspace, WorkspaceState } from "./types.js";

export function createSampleSourceWorkspace(): SourceWorkspace {
  return {
    id: "agent-graph",
    label: "Agent Graph Workspace",
    revision: 1,
    documents: [
      {
        id: "doc-product",
        label: "Product Scenarios",
        path: "blueprints/agent-graph/summary.md",
      },
      {
        id: "doc-ui",
        label: "UI Components",
        path: "packages/agent-graph-ui/src",
      },
      {
        id: "doc-protocol",
        label: "Contracts And Runtime",
        path: "packages/agent-graph-protocol/src",
      },
    ],
    nodes: [
      {
        id: "family-comprehension",
        documentId: "doc-product",
        label: "Whole-System Comprehension",
        kind: "scenario-family",
        summary: "Understand the complete multi-document graph and trust its completeness.",
      },
      {
        id: "family-compose",
        documentId: "doc-product",
        label: "View Composition",
        kind: "scenario-family",
        summary: "Compose persistent semantic slices and compare them together.",
      },
      {
        id: "family-inspection",
        documentId: "doc-product",
        label: "Graph-Native Inspection",
        kind: "scenario-family",
        summary: "Inspect local and hidden context without source text.",
      },
      {
        id: "family-editing",
        documentId: "doc-product",
        label: "Safe Editing",
        kind: "scenario-family",
        summary: "Perform trusted edits from visible graph layers.",
      },
      {
        id: "family-change",
        documentId: "doc-product",
        label: "Trust Under Change",
        kind: "scenario-family",
        summary: "Understand external changes and conflicts through graph-native diff.",
      },
      {
        id: "component-screen",
        documentId: "doc-ui",
        label: "AgentGraphScreen",
        kind: "component",
        summary: "Composes the screen layout and panels.",
      },
      {
        id: "component-canvas",
        documentId: "doc-ui",
        label: "AgentGraphCanvas",
        kind: "component",
        summary: "Owns the React Flow plane and renderers.",
      },
      {
        id: "component-layers",
        documentId: "doc-ui",
        label: "LayerWorkspacePanel",
        kind: "component",
        summary: "Manages layers and their arrangement.",
      },
      {
        id: "component-inspector",
        documentId: "doc-ui",
        label: "InspectorPanel",
        kind: "component",
        summary: "Owns selection details, rename, and connect flows.",
      },
      {
        id: "component-diff",
        documentId: "doc-ui",
        label: "DiffPanel",
        kind: "component",
        summary: "Explains change and diff layers.",
      },
      {
        id: "contract-workspace",
        documentId: "doc-protocol",
        label: "WorkspaceSnapshot",
        kind: "contract",
        summary: "Open workspace and layer persistence context.",
      },
      {
        id: "contract-graph",
        documentId: "doc-protocol",
        label: "GraphSnapshot",
        kind: "contract",
        summary: "Complete projected graph for the current revision.",
      },
      {
        id: "contract-diff",
        documentId: "doc-protocol",
        label: "GraphDiffSnapshot",
        kind: "contract",
        summary: "Old, new, and changed-only comparison state.",
      },
      {
        id: "contract-validation",
        documentId: "doc-protocol",
        label: "ValidationPayload",
        kind: "contract",
        summary: "Accepted or rejected edit with graph-native explanation.",
      },
      {
        id: "runtime-browser",
        documentId: "doc-protocol",
        label: "BrowserClient",
        kind: "runtime",
        summary: "Runs React and React Flow for the graph workspace.",
      },
      {
        id: "runtime-server",
        documentId: "doc-protocol",
        label: "BunGraphServer",
        kind: "runtime",
        summary: "Authoritative server for snapshots, validation, and persistence.",
      },
      {
        id: "runtime-filesystem",
        documentId: "doc-protocol",
        label: "WorkspaceFilesystem",
        kind: "runtime",
        summary: "Authoritative persistence layer for source and workspace sidecar state.",
      },
      {
        id: "workspace-op-reveal",
        documentId: "doc-product",
        label: "Reveal Hidden Context",
        kind: "workspace-op",
        summary: "Expands hidden context into temporary workspace state.",
      },
    ],
    edges: [
      {
        id: "edge-comp-1",
        sourceId: "family-comprehension",
        targetId: "component-screen",
        kind: "supports",
        label: "screen supports comprehension",
      },
      {
        id: "edge-comp-2",
        sourceId: "family-compose",
        targetId: "component-layers",
        kind: "supports",
        label: "layers support composition",
      },
      {
        id: "edge-comp-3",
        sourceId: "family-inspection",
        targetId: "component-inspector",
        kind: "supports",
        label: "inspector supports inspection",
      },
      {
        id: "edge-comp-4",
        sourceId: "family-change",
        targetId: "component-diff",
        kind: "supports",
        label: "diff panel supports trust under change",
      },
      {
        id: "edge-comp-5",
        sourceId: "component-screen",
        targetId: "component-canvas",
        kind: "contains",
        label: "screen contains canvas",
      },
      {
        id: "edge-comp-6",
        sourceId: "component-screen",
        targetId: "component-layers",
        kind: "contains",
        label: "screen contains layer workspace panel",
      },
      {
        id: "edge-comp-7",
        sourceId: "component-screen",
        targetId: "component-inspector",
        kind: "contains",
        label: "screen contains inspector",
      },
      {
        id: "edge-comp-8",
        sourceId: "component-screen",
        targetId: "component-diff",
        kind: "contains",
        label: "screen contains diff panel",
      },
      {
        id: "edge-contract-1",
        sourceId: "component-canvas",
        targetId: "contract-graph",
        kind: "depends-on",
        label: "canvas depends on graph snapshot",
      },
      {
        id: "edge-contract-2",
        sourceId: "component-layers",
        targetId: "contract-workspace",
        kind: "depends-on",
        label: "layers depend on workspace snapshot",
      },
      {
        id: "edge-contract-3",
        sourceId: "component-inspector",
        targetId: "contract-validation",
        kind: "depends-on",
        label: "inspector depends on validation payload",
      },
      {
        id: "edge-contract-4",
        sourceId: "component-diff",
        targetId: "contract-diff",
        kind: "depends-on",
        label: "diff panel depends on graph diff snapshot",
      },
      {
        id: "edge-runtime-1",
        sourceId: "component-canvas",
        targetId: "runtime-browser",
        kind: "implements",
        label: "canvas runs in browser client",
      },
      {
        id: "edge-runtime-2",
        sourceId: "contract-workspace",
        targetId: "runtime-server",
        kind: "implements",
        label: "workspace snapshot served by server",
      },
      {
        id: "edge-runtime-3",
        sourceId: "runtime-server",
        targetId: "runtime-filesystem",
        kind: "depends-on",
        label: "server persists through workspace filesystem",
      },
      {
        id: "edge-trace-1",
        sourceId: "family-editing",
        targetId: "workspace-op-reveal",
        kind: "traces-to",
        label: "editing may require hidden context reveal",
      },
      {
        id: "edge-trace-2",
        sourceId: "workspace-op-reveal",
        targetId: "component-inspector",
        kind: "supports",
        label: "reveal hidden context enters inspection flow",
      },
    ],
  };
}

export function createInitialWorkspaceState(): WorkspaceState {
  const layers: LayerDefinition[] = [
    {
      id: "layer-overview",
      label: "Overview",
      kind: "overview",
      nodeIds: [
        "family-comprehension",
        "family-compose",
        "family-inspection",
        "family-editing",
        "family-change",
      ],
      visible: true,
      x: 40,
      y: 40,
      derivedFromLayerId: null,
    },
  ];

  return {
    rootId: "agent-graph",
    revision: 1,
    layers,
    nodePositions: {},
  };
}
