export const agentishGraphImplementationPlan = {
  standard: "resolve-all-non-mechanical-implementation-decisions",
  appShell: {
    app: "apps/agentish-studio",
    rule: "Vite is a thin composition shell only.",
  },
  runtime: {
    browser: "React + Legend State + React Flow + Tailwind",
    server: "Bun HTTP + WSS authority",
    authority: {
      sourceWrites: "server-only",
      projection: "server-built",
      clientState: "session-only",
    },
  },
  packages: {
    "@agentish/graph-core": {
      path: "packages/agentish-graph-core",
      owns: [
        "parser",
        "semantic-model",
        "stable-identity",
        "projection-builder",
        "mutation-planner",
      ],
      dependsOn: [],
    },
    "@agentish/graph-protocol": {
      path: "packages/agentish-graph-protocol",
      owns: ["http-contracts", "ws-contracts"],
      dependsOn: ["@agentish/graph-core"],
    },
    "@agentish/graph-store": {
      path: "packages/agentish-graph-store",
      owns: ["legend-state", "client-actions"],
      dependsOn: ["@agentish/graph-core", "@agentish/graph-protocol"],
    },
    "@agentish/graph-ui": {
      path: "packages/agentish-graph-ui",
      owns: ["react-components", "react-flow-adapters", "tailwind-ui"],
      dependsOn: [
        "@agentish/graph-core",
        "@agentish/graph-protocol",
        "@agentish/graph-store",
      ],
    },
    "@agentish/graph-server": {
      path: "packages/agentish-graph-server",
      owns: [
        "bun-http-server",
        "bun-ws-server",
        "workspace-access",
        "file-watching",
        "mutation-execution",
      ],
      dependsOn: ["@agentish/graph-core", "@agentish/graph-protocol"],
    },
  },
  roots: {
    core: "packages/agentish-graph-core/src",
    protocol: "packages/agentish-graph-protocol/src",
    store: "packages/agentish-graph-store/src",
    ui: "packages/agentish-graph-ui/src",
    server: "packages/agentish-graph-server/src",
    studio: "apps/agentish-studio/src",
  },
  fileOwnership: {
    core: [
      "contracts/*",
      "parser/parse-agentish-document.ts",
      "semantic/build-semantic-model.ts",
      "identity/build-stable-id.ts",
      "projection/build-graph-projection.ts",
      "mutation/plan-source-mutation.ts",
    ],
    protocol: ["http.ts", "ws.ts"],
    store: ["agentish-graph-store.ts", "actions.ts"],
    ui: [
      "components/AgentishGraphScreen.tsx",
      "components/AgentishGraphCanvas.tsx",
      "components/AgentishGraphInspectorPane.tsx",
      "components/{AgentishGraphFileTreePane,AgentishGraphLayerPane,AgentishGraphLegendPane,AgentishGraphToolbar,AgentishGraphStatusBar}.tsx",
      "{renderers,reactflow}/*",
    ],
    server: [
      "config.ts",
      "http/create-http-server.ts",
      "ws/create-ws-server.ts",
      "session/session-registry.ts",
      "workspace/workspace-service.ts",
      "workspace/workspace-watcher.ts",
      "workspace/document-repository.ts",
      "mutation/apply-source-mutation.ts",
    ],
    studio: ["App.tsx", "main.tsx"],
  },
  decisions: {
    parsing: [
      "Use the TypeScript compiler API to parse Agentish-in-TypeScript.",
      "Extract define declarations, relationship chains, and when/then chains.",
    ],
    identity: [
      "Stable IDs derive from relative path plus semantic local meaning.",
      "Layout hints are keyed by stable ID.",
    ],
    projection: [
      "Projection is built on the server, never in the browser.",
      "Projection is recomputed from source plus layout hints.",
    ],
    layering: [
      "One layer per open document.",
      "Default layer order is lexicographic by relative path.",
    ],
    mutation: [
      "GraphMutationIntent is the only client write primitive.",
      "SourcePatchPlan is the only server write primitive.",
      "Client may be optimistic about selection and viewport, not source authority.",
    ],
    session: [
      "One writable session per workspace root.",
      "Missing patch revisions force full snapshot reload.",
    ],
    conflicts: [
      "Conflicts pause the pending mutation queue.",
      "Resolution choices are reload or discard local intent.",
    ],
    rendering: [
      "React Flow is an adapter over projection, never the source of truth.",
      "Portal edges represent cross-layer references only.",
    ],
  },
  store: {
    slices: [
      "session",
      "workspace",
      "graph",
      "inspector",
      "ui",
      "io",
    ] as const,
    actions: [
      "bootstrapConfig",
      "createSession",
      "connectSocket",
      "applyServerSnapshot",
      "applyServerPatch",
      "openDocument",
      "setSelection",
      "setViewport",
      "beginInspectorEdit",
      "commitInspectorDraft",
      "createNode",
      "connectHandles",
      "deleteSelection",
      "queueGraphIntent",
      "resolveConflict",
      "persistLayoutHint",
    ] as const,
  },
  transport: {
    http: [
      "GET /api/agentish-graph/config",
      "GET /api/agentish-graph/roots",
      "POST /api/agentish-graph/sessions",
      "GET /api/agentish-graph/sessions/:sessionId/snapshot",
      "DELETE /api/agentish-graph/sessions/:sessionId",
    ] as const,
    wss: {
      endpoint: "/api/agentish-graph/ws",
      client: [
        "client/hello",
        "client/open-root",
        "client/open-documents",
        "client/apply-intent",
        "client/persist-layout",
        "client/save-documents",
        "client/ping",
      ] as const,
      server: [
        "server/ready",
        "server/workspace-snapshot",
        "server/projection-snapshot",
        "server/projection-patch",
        "server/document-patched",
        "server/validation",
        "server/conflict",
        "server/file-changed",
        "server/error",
        "server/pong",
      ] as const,
    },
  },
  ui: {
    components: [
      "AgentishGraphScreen",
      "AgentishGraphCanvas",
      "AgentishGraphInspectorPane",
      "AgentishGraphFileTreePane",
      "AgentishGraphLayerPane",
      "AgentishGraphLegendPane",
      "AgentishGraphToolbar",
      "AgentishGraphStatusBar",
      "AgentishNodeCard",
      "AgentishGroupNode",
      "AgentishPortalEdge",
    ] as const,
  },
  invariants: [
    "UI and store packages never use filesystem APIs.",
    "Only the server writes documents.",
    "Equivalent meaning yields equivalent stable IDs across reprojection.",
    "Equal documents plus equal layout hints yield equal projection.",
    "Projection patches apply strictly in revision order.",
  ] as const,
  flows: {
    boot: [
      "mount graph screen",
      "fetch config",
      "fetch roots",
      "create session",
      "connect WSS",
      "exchange hello/ready",
    ],
    openRoot: [
      "open root",
      "receive workspace snapshot",
      "receive projection snapshot",
      "normalize snapshot into store maps",
    ],
    edit: [
      "queue graph intent",
      "server plans source patch",
      "server applies source patch",
      "server emits validation and projection patch",
    ],
    externalChange: [
      "server detects file change",
      "server reparses affected documents",
      "server emits projection patch or reload condition",
    ],
    conflict: [
      "server emits conflict",
      "store pauses affected mutation flow",
      "human chooses reload or discard local intent",
    ],
  },
} as const;
